export const playerData = {
    "player": {
        fullName: "Joel Farabee",
        slug: "joel-farabee",
        isWaiversExempt: true,
        isSlideEligible: true,
        isSPCExempt: true,
        age: 25,
        position: "LW",
        pos: "RW, LW",
        status: "NHL",
        acquisition: {
          type: "Trade",
          details: "The Philadelphia Flyers have acquired forwards Andrei Kuzmenko and Jakob Pelletier, along with a 2025 second-round pick and a 2025 seventh-round pick, from the Calgary Flames in exchange for forwards Joel Farabee and Morgan Frost. on Jan. 30 2025",
          acquisitionId: "PHI-CGY-2025-01-29",
        },
        playerId: 8480797,
        headshotUrl: "https://assets.nhle.com/mugs/nhl/latest/8480797.png",
        jerseyNumber: 86,
        shootsCatches: "L",
        birthdate: "Feb. 25, 2000",
        birthplace: "Syracuse, New York, USA",
        nationality: "USA",
        height: ['6\'0"', "183cm"],
        weight: ["186 lbs", "84kg"],
        elcSigningAge: "19",
        waiversAge: "19",
        teamSlug: "calgary-flames",
        teamTricode: "CGY",
        teamName: "Calgary Flames",
        teamPrimary: "#C8102E",
        teamSecondary: "#F1BE48",
        draft: {
          year: 2018,
          overall: 14,
          round: 1,
          pickInRound: 14,
          team: "PHI",
          gm: "Ron Hextall",
          gmSlug: "ron-hextall",
        },
        // New fields
        charity: {
          name: "Farabee Foundation for Youth Hockey",
          link: "https://example.com/farabee-foundation",
        },
        accruedSeasons: 3,
        proSeasons: 5,
        proExperience: 5,

      
      "contracts": [
        {
          "type": "Standard Contract (Extension)",
          "signedBy": "Chuck Fletcher",
          "length": "6 years",
          "value": "$30,000,000",
          "expiryStatus": "UFA",
          "capPercent": "6.14",
          "signingTeam": "Philadelphia Flyers",
          "signingDate": "Sep. 2, 2021",
          "description": "Joel Farabee signed a 6 year, $30,000,000 contract with the Philadelphia Flyers on Sep. 2, 2021. The contract has a cap hit of $5,000,000.",
          "buriedCaphit": "$3,850,000",
          "loadType": "back-loaded",
          "details": [
            {
              "season": "2022-23",
              "clause": "",
              "capHit": "$5,000,000",
              "aav": "$5,000,000",
              "performanceBonus": "$0",
              "signingBonus": "$2,000,000",
              "baseSalary": "$1,000,000",
              "totalSalary": "$3,000,000",
              "minorsSalary": "$3,000,000"
            },
            {
              "season": "2023-24",
              "clause": "",
              "capHit": "$5,000,000",
              "aav": "$5,000,000",
              "performanceBonus": "$0",
              "signingBonus": "$2,000,000",
              "baseSalary": "$2,250,000",
              "totalSalary": "$4,250,000",
              "minorsSalary": "$4,250,000"
            },
            {
              "season": "2024-25",
              "clause": "",
              "capHit": "$5,000,000",
              "aav": "$5,000,000",
              "performanceBonus": "$0",
              "signingBonus": "$2,000,000",
              "baseSalary": "$3,000,000",
              "totalSalary": "$5,000,000",
              "minorsSalary": "$5,000,000"
            },
            {
              "season": "2025-26",
              "clause": "",
              "capHit": "$5,000,000",
              "aav": "$5,000,000",
              "performanceBonus": "$0",
              "signingBonus": "$1,500,000",
              "baseSalary": "$4,250,000",
              "totalSalary": "$5,750,000",
              "minorsSalary": "$5,750,000"
            },
            {
              "season": "2026-27",
              "clause": "",
              "capHit": "$5,000,000",
              "aav": "$5,000,000",
              "performanceBonus": "$0",
              "signingBonus": "$0",
              "baseSalary": "$6,000,000",
              "totalSalary": "$6,000,000",
              "minorsSalary": "$6,000,000"
            },
            {
              "season": "2027-28",
              "clause": "NMC",
              "capHit": "$5,000,000",
              "aav": "$5,000,000",
              "performanceBonus": "$0",
              "signingBonus": "$0",
              "baseSalary": "$6,000,000",
              "totalSalary": "$6,000,000",
              "minorsSalary": "$6,000,000"
            }
          ],
          "qualifyingOffer": "",
          "clauseDetails": "",
          "buyout": "",
          "arbitration": "",
          "signedBySlug": "chuck-fletcher"
        },
        {
          "type": "Entry-Level Contract",
          "signedBy": "Chuck Fletcher",
          "length": "3 years",
          "value": "$4,275,000",
          "expiryStatus": "RFA",
          "capPercent": "1.16",
          "signingTeam": "Philadelphia Flyers",
          "signingDate": "Mar. 25, 2019",
          "description": "Joel Farabee signed a 3 year, $4,275,000 contract with the Philadelphia Flyers on Mar. 25, 2019. The contract has a cap hit of $925,000.",
          "buriedCaphit": "$3,850,000",
          "loadType": "back-loaded",
          "details": [
            {
              "season": "2019-20",
              "clause": "",
              "capHit": "$925,000",
              "aav": "$1,425,000",
              "performanceBonus": "$400,000",
              "signingBonus": "$92,500",
              "baseSalary": "$832,500",
              "totalSalary": "$925,000",
              "minorsSalary": "$70,000"
            },
            {
              "season": "2020-21",
              "clause": "",
              "capHit": "$925,000",
              "aav": "$1,425,000",
              "performanceBonus": "$500,000",
              "signingBonus": "$92,500",
              "baseSalary": "$832,500",
              "totalSalary": "$925,000",
              "minorsSalary": "$70,000"
            },
            {
              "season": "2021-22",
              "clause": "",
              "capHit": "$925,000",
              "aav": "$1,425,000",
              "performanceBonus": "$600,000",
              "signingBonus": "$92,500",
              "baseSalary": "$832,500",
              "totalSalary": "$925,000",
              "minorsSalary": "$70,000"
            }
          ],
          "qualifyingOffer": "$874,125",
          "clauseDetails": "",
          "buyout": "",
          "arbitration": "",
          "signedBySlug": "chuck-fletcher"
        }
      ],
      "stats": [
        {
          "season": "2012-13",
          "team": "Buffalo Jr. Sabres",
          "league": "QC Int PW AA Elite",
          "gp": 4,
          "g": 5,
          "a": 1,
          "p": 6,
          "plusMinus": 0,
          "pim": 2,
          "toi": 0,
          "foPct": 0,
          "gwg": 0,
          "otG": 0,
          "ppg": 0,
          "ppp": 0,
          "shootingPct": 0,
          "shG": 0,
          "shP": 0,
          "shots": 0,
          "ptsPerG": 1.5,
          "platformSeason": null,
          "diff": null
        },
        {
          "season": "2014-15",
          "team": "Selects Hockey Academy 16U",
          "league": "USPHL 16U",
          "gp": 28,
          "g": 8,
          "a": 25,
          "p": 33,
          "plusMinus": 0,
          "pim": 16,
          "toi": 0,
          "foPct": 0,
          "gwg": 0,
          "otG": 0,
          "ppg": 0,
          "ppp": 0,
          "shootingPct": 0,
          "shG": 0,
          "shP": 0,
          "shots": 0,
          "playoffs": {
            "season": "2014-15",
            "team": "Selects Hockey Academy 16U",
            "league": "USPHL 16U",
            "gp": 3,
            "g": 0,
            "a": 2,
            "p": 2,
            "plusMinus": 0,
            "pim": 0,
            "toi": 0,
            "foPct": 0,
            "gwg": 0,
            "otG": 0,
            "ppg": 0,
            "ppp": 0,
            "shootingPct": 0,
            "shG": 0,
            "shP": 0,
            "shots": 0
          },
          "ptsPerG": 1.18,
          "platformSeason": null,
          "diff": null
        },
        {
          "season": "2014-15",
          "team": "East Coast Selects O U15",
          "league": "WSI U15",
          "gp": 0,
          "playoffs": {
            "season": "2014-15",
            "team": "East Coast Selects O U15",
            "league": "WSI U15",
            "gp": 7,
            "g": 4,
            "a": 15,
            "p": 19,
            "plusMinus": 0,
            "pim": 0,
            "toi": 0,
            "foPct": 0,
            "gwg": 0,
            "otG": 0,
            "ppg": 0,
            "ppp": 0,
            "shootingPct": 0,
            "shG": 0,
            "shP": 0,
            "shots": 0
          },
          "ptsPerG": 0,
          "platformSeason": null,
          "diff": null
        },
        {
          "season": "2015-16",
          "team": "Team Black",
          "league": "USA-S15",
          "gp": 5,
          "g": 0,
          "a": 3,
          "p": 3,
          "plusMinus": 0,
          "pim": 0,
          "toi": 0,
          "foPct": 0,
          "gwg": 0,
          "otG": 0,
          "ppg": 0,
          "ppp": 0,
          "shootingPct": 0,
          "shG": 0,
          "shP": 0,
          "shots": 0,
          "ptsPerG": 0.6,
          "platformSeason": null,
          "diff": null
        },
        {
          "season": "2015-16",
          "team": "South Kent School 16U AAA",
          "league": "USPHL 16U",
          "gp": 27,
          "g": 19,
          "a": 30,
          "p": 49,
          "plusMinus": 0,
          "pim": 18,
          "toi": 0,
          "foPct": 0,
          "gwg": 0,
          "otG": 0,
          "ppg": 0,
          "ppp": 0,
          "shootingPct": 0,
          "shG": 0,
          "shP": 0,
          "shots": 0,
          "playoffs": {
            "season": "2015-16",
            "team": "South Kent School 16U AAA",
            "league": "USPHL 16U",
            "gp": 3,
            "g": 5,
            "a": 5,
            "p": 10,
            "plusMinus": 0,
            "pim": 6,
            "toi": 0,
            "foPct": 0,
            "gwg": 0,
            "otG": 0,
            "ppg": 0,
            "ppp": 0,
            "shootingPct": 0,
            "shG": 0,
            "shP": 0,
            "shots": 0
          },
          "ptsPerG": 1.81,
          "platformSeason": null,
          "diff": null
        },
        {
          "season": "2016-17",
          "team": "USNTDP Juniors",
          "league": "USHL",
          "gp": 30,
          "g": 12,
          "a": 11,
          "p": 23,
          "plusMinus": 0,
          "pim": 22,
          "toi": 0,
          "foPct": 0,
          "gwg": 0,
          "otG": 0,
          "ppg": 0,
          "ppp": 0,
          "shootingPct": 0,
          "shG": 0,
          "shP": 0,
          "shots": 0,
          "ptsPerG": 0.77,
          "platformSeason": null,
          "diff": null
        },
        {
          "season": "2016-17",
          "team": "USA U17",
          "league": "WHC-17",
          "gp": 5,
          "g": 4,
          "a": 2,
          "p": 6,
          "plusMinus": 0,
          "pim": 6,
          "toi": 0,
          "foPct": 0,
          "gwg": 0,
          "otG": 0,
          "ppg": 0,
          "ppp": 0,
          "shootingPct": 0,
          "shG": 0,
          "shP": 0,
          "shots": 0,
          "ptsPerG": 1.2,
          "platformSeason": null,
          "diff": null
        },
        {
          "season": "2016-17",
          "team": "USA U18",
          "league": "WJC-18",
          "gp": 7,
          "g": 3,
          "a": 3,
          "p": 6,
          "plusMinus": 2,
          "pim": 6,
          "toi": 0,
          "foPct": 0,
          "gwg": 0,
          "otG": 0,
          "ppg": 0,
          "ppp": 0,
          "shootingPct": 0,
          "shG": 0,
          "shP": 0,
          "shots": 0,
          "ptsPerG": 0.86,
          "platformSeason": null,
          "diff": null
        },
        {
          "season": "2016-17",
          "team": "U.S. National U18 Team",
          "league": "USDP",
          "gp": 22,
          "g": 8,
          "a": 11,
          "p": 19,
          "plusMinus": 0,
          "pim": 10,
          "toi": 0,
          "foPct": 0,
          "gwg": 0,
          "otG": 0,
          "ppg": 0,
          "ppp": 0,
          "shootingPct": 0,
          "shG": 0,
          "shP": 0,
          "shots": 0,
          "ptsPerG": 0.86,
          "platformSeason": null,
          "diff": null
        },
        {
          "season": "2016-17",
          "team": "U.S. National U17 Team",
          "league": "USDP",
          "gp": 42,
          "g": 17,
          "a": 14,
          "p": 31,
          "plusMinus": 0,
          "pim": 48,
          "toi": 0,
          "foPct": 0,
          "gwg": 0,
          "otG": 0,
          "ppg": 0,
          "ppp": 0,
          "shootingPct": 0,
          "shG": 0,
          "shP": 0,
          "shots": 0,
          "ptsPerG": 0.74,
          "platformSeason": null,
          "diff": null
        },
        {
          "season": "2017-18",
          "team": "USNTDP Juniors",
          "league": "USHL",
          "gp": 26,
          "g": 15,
          "a": 25,
          "p": 40,
          "plusMinus": 26,
          "pim": 18,
          "toi": 0,
          "foPct": 0,
          "gwg": 0,
          "otG": 0,
          "ppg": 0,
          "ppp": 0,
          "shootingPct": 0,
          "shG": 0,
          "shP": 0,
          "shots": 0,
          "ptsPerG": 1.54,
          "platformSeason": null,
          "diff": null
        },
        {
          "season": "2017-18",
          "team": "USA U18",
          "league": "WJC-18",
          "gp": 7,
          "g": 4,
          "a": 4,
          "p": 8,
          "plusMinus": 1,
          "pim": 6,
          "toi": 0,
          "foPct": 0,
          "gwg": 0,
          "otG": 0,
          "ppg": 0,
          "ppp": 0,
          "shootingPct": 0,
          "shG": 0,
          "shP": 0,
          "shots": 0,
          "ptsPerG": 1.14,
          "platformSeason": null,
          "diff": null
        },
        {
          "season": "2017-18",
          "team": "U.S. National U18 Team",
          "league": "USDP",
          "gp": 62,
          "g": 33,
          "a": 43,
          "p": 76,
          "plusMinus": 0,
          "pim": 44,
          "toi": 0,
          "foPct": 0,
          "gwg": 0,
          "otG": 0,
          "ppg": 0,
          "ppp": 0,
          "shootingPct": 0,
          "shG": 0,
          "shP": 0,
          "shots": 0,
          "ptsPerG": 1.23,
          "platformSeason": null,
          "diff": null
        },
        {
          "season": "2018-19",
          "team": "Boston Univ.",
          "league": "NCAA",
          "gp": 37,
          "g": 17,
          "a": 19,
          "p": 36,
          "plusMinus": 4,
          "pim": 57,
          "toi": 0,
          "foPct": 0,
          "gwg": 0,
          "otG": 0,
          "ppg": 0,
          "ppp": 0,
          "shootingPct": 0,
          "shG": 0,
          "shP": 0,
          "shots": 0,
          "ptsPerG": 0.97,
          "platformSeason": "2018-19",
          "diff": null
        },
        {
          "season": "2018-19",
          "team": "USA U20",
          "league": "WJC-20",
          "gp": 7,
          "g": 3,
          "a": 2,
          "p": 5,
          "plusMinus": 2,
          "pim": 2,
          "toi": 0,
          "foPct": 0,
          "gwg": 0,
          "otG": 0,
          "ppg": 0,
          "ppp": 0,
          "shootingPct": 0,
          "shG": 0,
          "shP": 0,
          "shots": 0,
          "ptsPerG": 0.71,
          "platformSeason": "2018-19",
          "diff": null
        },
        {
          "season": "2019-20",
          "team": "Philadelphia Flyers",
          "league": "NHL",
          "gp": 52,
          "g": 8,
          "a": 13,
          "p": 21,
          "plusMinus": 6,
          "pim": 39,
          "toi": "14:06",
          "foPct": 0.3,
          "gwg": 1,
          "otG": 0,
          "ppg": 1,
          "ppp": 2,
          "shootingPct": 0.099,
          "shG": 0,
          "shP": 0,
          "shots": 81,
          "playoffs": {
            "season": "2019-20",
            "team": "Philadelphia Flyers",
            "league": "NHL",
            "gp": 12,
            "g": 3,
            "a": 2,
            "p": 5,
            "plusMinus": -2,
            "pim": 4,
            "toi": "14:29",
            "foPct": 0.25,
            "gwg": 1,
            "otG": 0,
            "ppg": 1,
            "ppp": 1,
            "shootingPct": 0.158,
            "shG": 0,
            "shP": 0,
            "shots": 19
          },
          "ptsPerG": 0.4,
          "platformSeason": null,
          "diff": null
        },
        {
          "season": "2019-20",
          "team": "Lehigh Valley Phantoms",
          "league": "AHL",
          "gp": 5,
          "g": 3,
          "a": 1,
          "p": 4,
          "plusMinus": 3,
          "pim": 2,
          "toi": 0,
          "foPct": 0,
          "gwg": 0,
          "otG": 0,
          "ppg": 0,
          "ppp": 0,
          "shootingPct": 0,
          "shG": 0,
          "shP": 0,
          "shots": 0,
          "ptsPerG": 0.8,
          "platformSeason": null,
          "diff": null
        },
        {
          "season": "2020-21",
          "team": "Philadelphia Flyers",
          "league": "NHL",
          "gp": 55,
          "g": 20,
          "a": 18,
          "p": 38,
          "plusMinus": 0,
          "pim": 28,
          "toi": "16:01",
          "foPct": 0.4,
          "gwg": 1,
          "otG": 0,
          "ppg": 3,
          "ppp": 7,
          "shootingPct": 0.164,
          "shG": 0,
          "shP": 0,
          "shots": 122,
          "ptsPerG": 0.69,
          "platformSeason": null,
          "diff": {
            "gp": "3.00",
            "g": "12.00",
            "a": "5.00",
            "p": "17.00",
            "plusMinus": "-6.00",
            "pim": "-11.00",
            "foPct": "0.10",
            "gwg": "0.00",
            "otG": "0.00",
            "ppg": "2.00",
            "ppp": "5.00",
            "shootingPct": "0.07",
            "shG": "0.00",
            "shP": "0.00",
            "shots": "41.00"
          }
        },
        {
          "season": "2021-22",
          "team": "Philadelphia Flyers",
          "league": "NHL",
          "gp": 63,
          "g": 17,
          "a": 17,
          "p": 34,
          "plusMinus": -11,
          "pim": 50,
          "toi": "17:35",
          "foPct": 0.286713,
          "gwg": 1,
          "otG": 0,
          "ppg": 1,
          "ppp": 3,
          "shootingPct": 0.143,
          "shG": 1,
          "shP": 1,
          "shots": 119,
          "ptsPerG": 0.54,
          "platformSeason": "2021-22",
          "diff": {
            "gp": "8.00",
            "g": "-3.00",
            "a": "-1.00",
            "p": "-4.00",
            "plusMinus": "-11.00",
            "pim": "22.00",
            "foPct": "-0.11",
            "gwg": "0.00",
            "otG": "0.00",
            "ppg": "-2.00",
            "ppp": "-4.00",
            "shootingPct": "-0.02",
            "shG": "1.00",
            "shP": "1.00",
            "shots": "-3.00"
          }
        },
        {
          "season": "2022-23",
          "team": "Philadelphia Flyers",
          "league": "NHL",
          "gp": 82,
          "g": 15,
          "a": 24,
          "p": 39,
          "plusMinus": -1,
          "pim": 41,
          "toi": "17:01",
          "foPct": 0.355556,
          "gwg": 1,
          "otG": 0,
          "ppg": 0,
          "ppp": 2,
          "shootingPct": 0.103448,
          "shG": 0,
          "shP": 0,
          "shots": 145,
          "ptsPerG": 0.48,
          "platformSeason": null,
          "diff": {
            "gp": "19.00",
            "g": "-2.00",
            "a": "7.00",
            "p": "5.00",
            "plusMinus": "10.00",
            "pim": "-9.00",
            "foPct": "0.07",
            "gwg": "0.00",
            "otG": "0.00",
            "ppg": "-1.00",
            "ppp": "-1.00",
            "shootingPct": "-0.04",
            "shG": "-1.00",
            "shP": "-1.00",
            "shots": "26.00"
          }
        },
        {
          "season": "2023-24",
          "team": "Philadelphia Flyers",
          "league": "NHL",
          "gp": 82,
          "g": 22,
          "a": 28,
          "p": 50,
          "plusMinus": -13,
          "pim": 37,
          "toi": "16:11",
          "foPct": 0.375,
          "gwg": 2,
          "otG": 1,
          "ppg": 2,
          "ppp": 7,
          "shootingPct": 0.120879,
          "shG": 0,
          "shP": 0,
          "shots": 182,
          "ptsPerG": 0.61,
          "platformSeason": null,
          "diff": {
            "gp": "0.00",
            "g": "7.00",
            "a": "4.00",
            "p": "11.00",
            "plusMinus": "-12.00",
            "pim": "-4.00",
            "foPct": "0.02",
            "gwg": "1.00",
            "otG": "1.00",
            "ppg": "2.00",
            "ppp": "5.00",
            "shootingPct": "0.02",
            "shG": "0.00",
            "shP": "0.00",
            "shots": "37.00"
          }
        },
        {
          "season": "2023-24",
          "team": "USA",
          "league": "WC",
          "gp": 8,
          "g": 1,
          "a": 1,
          "p": 2,
          "plusMinus": 2,
          "pim": 0,
          "toi": 0,
          "foPct": 0,
          "gwg": 0,
          "otG": 0,
          "ppg": 0,
          "ppp": 0,
          "shootingPct": 0,
          "shG": 0,
          "shP": 0,
          "shots": 0,
          "ptsPerG": 0.25,
          "platformSeason": null,
          "diff": null
        },
        {
          "season": "2023-24",
          "team": "Team USA",
          "league": "International",
          "gp": 1,
          "g": 1,
          "a": 0,
          "p": 1,
          "plusMinus": 1,
          "pim": 0,
          "toi": 0,
          "foPct": 0,
          "gwg": 0,
          "otG": 0,
          "ppg": 0,
          "ppp": 0,
          "shootingPct": 0,
          "shG": 0,
          "shP": 0,
          "shots": 0,
          "ptsPerG": 1,
          "platformSeason": null,
          "diff": null
        },
        {
          "season": "2024-25",
          "team": "Philadelphia Flyers",
          "league": "NHL",
          "gp": 50,
          "g": 8,
          "a": 11,
          "p": 19,
          "plusMinus": -12,
          "pim": 26,
          "toi": "15:12",
          "foPct": 0.305556,
          "gwg": 0,
          "otG": 0,
          "ppg": 0,
          "ppp": 3,
          "shootingPct": 0.080808,
          "shG": 0,
          "shP": 0,
          "shots": 99,
          "ptsPerG": 0.38,
          "platformSeason": null,
          "diff": {
            "gp": "-32.00",
            "g": "-14.00",
            "a": "-17.00",
            "p": "-31.00",
            "plusMinus": "1.00",
            "pim": "-11.00",
            "foPct": "-0.07",
            "gwg": "-2.00",
            "otG": "-1.00",
            "ppg": "-2.00",
            "ppp": "-4.00",
            "shootingPct": "-0.04",
            "shG": "0.00",
            "shP": "0.00",
            "shots": "-83.00"
          }
        },
        {
          "season": "2024-25",
          "team": "Calgary Flames",
          "league": "NHL",
          "gp": 31,
          "g": 3,
          "a": 3,
          "p": 6,
          "plusMinus": -5,
          "pim": 8,
          "toi": "14:26",
          "foPct": 0.538462,
          "gwg": 1,
          "otG": 0,
          "ppg": 0,
          "ppp": 1,
          "shootingPct": 0.057692,
          "shG": 0,
          "shP": 0,
          "shots": 52,
          "ptsPerG": 0.19,
          "platformSeason": null,
          "diff": {
            "gp": "-19.00",
            "g": "-5.00",
            "a": "-8.00",
            "p": "-13.00",
            "plusMinus": "7.00",
            "pim": "-18.00",
            "foPct": "0.23",
            "gwg": "1.00",
            "otG": "0.00",
            "ppg": "0.00",
            "ppp": "-2.00",
            "shootingPct": "-0.02",
            "shG": "0.00",
            "shP": "0.00",
            "shots": "-47.00"
          }
        },
        {
          "season": "2025-26",
          "team": "Calgary Flames",
          "league": "NHL",
          "gp": 68,
          "g": 15,
          "a": 15,
          "p": 30,
          "plusMinus": -11,
          "pim": 24,
          "toi": "16:51",
          "foPct": 0.44,
          "gwg": 2,
          "otG": 0,
          "ppg": 1,
          "ppp": 3,
          "shootingPct": 0.128205,
          "shG": 4,
          "shP": 5,
          "shots": 117,
          "ptsPerG": 0.44,
          "platformSeason": null,
          "diff": {
            "gp": "37.00",
            "g": "12.00",
            "a": "12.00",
            "p": "24.00",
            "plusMinus": "-6.00",
            "pim": "16.00",
            "foPct": "-0.10",
            "gwg": "1.00",
            "otG": "0.00",
            "ppg": "1.00",
            "ppp": "2.00",
            "shootingPct": "0.07",
            "shG": "4.00",
            "shP": "5.00",
            "shots": "65.00"
          }
        }
      ],
      "careerGamesPlayed": 346,
      "careerSeasonsPlayed": 5,
      "positions": {
        "RW": 58,
        "LW": 30
      },
      "nhlDays": {
        "2024-25": 12,
        "lastUpdated": "2024-10-09T13:45:52.157Z"
      },
      "transactions": [
        {
          id: 0,
          "date": "Jan. 30, 2026",
          "team": "SJS",
          "type": "TRADE",
          "details": "The Calgary Flames have traded Joel Farabee to the San Jose Sharks in exhange for a 2nd round draft pick.",
        },
        {
          id: 1,
          "date": "Jan. 30, 2025",
          "team": "CGY",
          "type": "TRADE",
          "details": "The Philadelphia Flyers have acquired forwards Andrei Kuzmenko and Jakob Pelletier, along with a 2025 second-round pick and a 2025 seventh-round pick, from the Calgary Flames in exchange for forwards Joel Farabee and Morgan Frost.",
        },
        {
          id: 2,
          "date": "Sep. 2, 2021",
          "team": "PHI",
          "type": "SIGNING-EXT",
          "details": "Signed a Standard Contract (Extension) for 6 years with Philadelphia Flyers"
        },
        {
          id: 3,
          "date": "Mar. 25, 2019",
          "team": "PHI",
          "type": "SIGNING-ELC",
          "details": "Signed a Entry-Level Contract for 3 years with Philadelphia Flyers"
        },
        {
          id: 4,
          "date": "June 22, 2018",
          "team": "PHI",
          "type": "DRAFT",
          "details": "Drafted round 1, #14 Overall"
        }
      ],
      "acquisitionTradeId": "2025-01-30-PHI-CGY",
      "epId": 334036,
      "epSlug": "joel-farabee",
      "officialPosition": "LW",
      "deployment": [
        {
          "date": "2025-10-07",
          "status": "active",
          "position": "lw",
          "line": "f1"
        },
        {
          "date": "2025-10-08",
          "status": "active",
          "position": "lw",
          "line": "f1"
        },
        {
          "date": "2025-10-09",
          "status": "active",
          "position": "lw",
          "line": "f1"
        },
        {
          "date": "2025-10-10",
          "status": "active",
          "position": "lw",
          "line": "f2"
        },
        {
          "date": "2025-10-11",
          "status": "active",
          "position": "lw",
          "line": "f2"
        },
        {
          "date": "2025-10-13",
          "status": "active",
          "position": "lw",
          "line": "f2"
        },
        {
          "date": "2025-10-16",
          "status": "active",
          "position": "lw",
          "line": "f2"
        },
        {
          "date": "2025-10-17",
          "status": "active",
          "position": "rw",
          "line": "f1"
        },
        {
          "date": "2025-10-19",
          "status": "active",
          "position": "rw",
          "line": "f1"
        },
        {
          "date": "2025-10-20",
          "status": "active",
          "position": "rw",
          "line": "f1"
        },
        {
          "date": "2025-10-24",
          "status": "active",
          "position": "lw",
          "line": "f3"
        },
        {
          "date": "2025-10-25",
          "status": "active",
          "position": "lw",
          "line": "f3"
        },
        {
          "date": "2025-10-26",
          "status": "active",
          "position": "lw",
          "line": "f3"
        },
        {
          "date": "2025-10-28",
          "status": "active",
          "position": "lw",
          "line": "f3"
        },
        {
          "date": "2025-10-29",
          "status": "active",
          "position": "rw",
          "line": "f3"
        },
        {
          "date": "2025-10-30",
          "status": "active",
          "position": "lw",
          "line": "f3"
        },
        {
          "date": "2025-11-01",
          "status": "active",
          "position": "lw",
          "line": "f3"
        },
        {
          "date": "2025-11-02",
          "status": "active",
          "position": "lw",
          "line": "f3"
        },
        {
          "date": "2025-11-03",
          "status": "active",
          "position": "lw",
          "line": "f1"
        },
        {
          "date": "2025-11-04",
          "status": "active",
          "position": "rw",
          "line": "f1"
        },
        {
          "date": "2025-11-05",
          "status": "active",
          "position": "rw",
          "line": "f1"
        },
        {
          "date": "2025-11-07",
          "status": "active",
          "position": "rw",
          "line": "f1"
        },
        {
          "date": "2025-11-09",
          "status": "active",
          "position": "rw",
          "line": "f1"
        },
        {
          "date": "2025-11-10",
          "status": "active",
          "position": "rw",
          "line": "f1"
        },
        {
          "date": "2025-11-11",
          "status": "active",
          "position": "rw",
          "line": "f1"
        },
        {
          "date": "2025-11-13",
          "status": "active",
          "position": "lw",
          "line": "f1"
        },
        {
          "date": "2025-11-15",
          "status": "active",
          "position": "rw",
          "line": "f1"
        },
        {
          "date": "2025-11-16",
          "status": "active",
          "position": "lw",
          "line": "f3"
        },
        {
          "date": "2025-11-18",
          "status": "active",
          "position": "rw",
          "line": "f2"
        },
        {
          "date": "2025-11-19",
          "status": "active",
          "position": "rw",
          "line": "f2"
        },
        {
          "date": "2025-11-20",
          "status": "active",
          "position": "rw",
          "line": "f2"
        },
        {
          "date": "2025-11-24",
          "status": "active",
          "position": "rw",
          "line": "f2"
        },
        {
          "date": "2025-11-28",
          "status": "active",
          "position": "rw",
          "line": "f2"
        },
        {
          "date": "2025-11-30",
          "status": "active",
          "position": "rw",
          "line": "f2"
        },
        {
          "date": "2025-12-01",
          "status": "active",
          "position": "rw",
          "line": "f2"
        },
        {
          "date": "2025-12-03",
          "status": "active",
          "position": "rw",
          "line": "f2"
        },
        {
          "date": "2025-12-04",
          "status": "active",
          "position": "rw",
          "line": "f2"
        },
        {
          "date": "2025-12-08",
          "status": "active",
          "position": "rw",
          "line": "f2"
        },
        {
          "date": "2025-12-10",
          "status": "active",
          "position": "rw",
          "line": "f2"
        },
        {
          "date": "2025-12-11",
          "status": "active",
          "position": "rw",
          "line": "f2"
        },
        {
          "date": "2025-12-15",
          "status": "active",
          "position": "lw",
          "line": "f2"
        },
        {
          "date": "2025-12-17",
          "status": "active",
          "position": "lw",
          "line": "f2"
        },
        {
          "date": "2025-12-19",
          "status": "active",
          "position": "lw",
          "line": "f2"
        },
        {
          "date": "2025-12-21",
          "status": "active",
          "position": "lw",
          "line": "f1"
        },
        {
          "date": "2025-12-27",
          "status": "active",
          "position": "lw",
          "line": "f1"
        },
        {
          "date": "2025-12-29",
          "status": "active",
          "position": "lw",
          "line": "f1"
        },
        {
          "date": "2025-12-30",
          "status": "active",
          "position": "lw",
          "line": "f1"
        },
        {
          "date": "2025-12-31",
          "status": "active",
          "position": "rw",
          "line": "f1"
        },
        {
          "date": "2026-01-01",
          "status": "active",
          "position": "rw",
          "line": "f1"
        },
        {
          "date": "2026-01-03",
          "status": "active",
          "position": "rw",
          "line": "f1"
        },
        {
          "date": "2026-01-05",
          "status": "active",
          "position": "rw",
          "line": "f1"
        },
        {
          "date": "2026-01-06",
          "status": "active",
          "position": "rw",
          "line": "f1"
        },
        {
          "date": "2026-01-07",
          "status": "active",
          "position": "lw",
          "line": "f1"
        },
        {
          "date": "2026-01-08",
          "status": "active",
          "position": "rw",
          "line": "f3"
        },
        {
          "date": "2026-01-09",
          "status": "active",
          "position": "rw",
          "line": "f1"
        },
        {
          "date": "2026-01-10",
          "status": "active",
          "position": "rw",
          "line": "f1"
        },
        {
          "date": "2026-01-11",
          "status": "active",
          "position": "rw",
          "line": "f1"
        },
        {
          "date": "2026-01-15",
          "status": "active",
          "position": "rw",
          "line": "f3"
        },
        {
          "date": "2026-01-16",
          "status": "active",
          "position": "rw",
          "line": "f3"
        },
        {
          "date": "2026-01-17",
          "status": "active",
          "position": "rw",
          "line": "f3"
        },
        {
          "date": "2026-01-18",
          "status": "active",
          "position": "rw",
          "line": "f3"
        },
        {
          "date": "2026-01-19",
          "status": "active",
          "position": "rw",
          "line": "f3"
        },
        {
          "date": "2026-01-20",
          "status": "active",
          "position": "rw",
          "line": "f3"
        },
        {
          "date": "2026-01-21",
          "status": "active",
          "position": "rw",
          "line": "f3"
        },
        {
          "date": "2026-01-22",
          "status": "active",
          "position": "rw",
          "line": "f3"
        },
        {
          "date": "2026-01-24",
          "status": "active",
          "position": "rw",
          "line": "f2"
        },
        {
          "date": "2026-01-25",
          "status": "active",
          "position": "lw",
          "line": "f4"
        },
        {
          "date": "2026-01-29",
          "status": "active",
          "position": "lw",
          "line": "f4"
        },
        {
          "date": "2026-01-30",
          "status": "active",
          "position": "lw",
          "line": "f4"
        },
        {
          "date": "2026-01-31",
          "status": "active",
          "position": "rw",
          "line": "f2"
        },
        {
          "date": "2026-02-02",
          "status": "active",
          "position": "rw",
          "line": "f2"
        },
        {
          "date": "2026-02-04",
          "status": "active",
          "position": "rw",
          "line": "f2"
        },
        {
          "date": "2026-02-05",
          "status": "active",
          "position": "rw",
          "line": "f2"
        },
        {
          "date": "2026-02-23",
          "status": "active",
          "position": "rw",
          "line": "f2"
        },
        {
          "date": "2026-02-25",
          "status": "active",
          "position": "rw",
          "line": "f2"
        },
        {
          "date": "2026-02-27",
          "status": "active",
          "position": "rw",
          "line": "f1"
        },
        {
          "date": "2026-03-01",
          "status": "active",
          "position": "rw",
          "line": "f1"
        },
        {
          "date": "2026-03-02",
          "status": "active",
          "position": "rw",
          "line": "f1"
        },
        {
          "date": "2026-03-03",
          "status": "active",
          "position": "rw",
          "line": "f1"
        },
        {
          "date": "2026-03-05",
          "status": "active",
          "position": "rw",
          "line": "f1"
        },
        {
          "date": "2026-03-06",
          "status": "active",
          "position": "rw",
          "line": "f2"
        },
        {
          "date": "2026-03-08",
          "status": "active",
          "position": "rw",
          "line": "f2"
        },
        {
          "date": "2026-03-09",
          "status": "active",
          "position": "lw",
          "line": "f1"
        },
        {
          "date": "2026-03-10",
          "status": "active",
          "position": "lw",
          "line": "f1"
        },
        {
          "date": "2026-03-12",
          "status": "active",
          "position": "rw",
          "line": "f1"
        },
        {
          "date": "2026-03-14",
          "status": "active",
          "position": "rw",
          "line": "f1"
        },
        {
          "date": "2026-03-16",
          "status": "active",
          "position": "rw",
          "line": "f1"
        },
        {
          "date": "2026-03-18",
          "status": "active",
          "position": "rw",
          "line": "f1"
        }
      ]
    },
    "teamMates": [
      "jonathan-huberdeau",
      "blake-coleman",
      "mikael-backlund",
      "yegor-sharangovich",
      "ryan-lomberg",
      "connor-zary",
      "matt-coronato",
      "joel-farabee",
      "morgan-frost",
      "adam-klapka",
      "samuel-honzek",
      "john-beecher",
      "martin-pospisil",
      "victor-olofsson",
      "ryan-strome",
      "matvei-gridin",
      "jake-bean",
      "brayden-pachal",
      "kevin-bahl",
      "joel-hanley",
      "yan-kuznetsov",
      "zach-whitecloud",
      "zayne-parekh",
      "olli-maatta",
      "hunter-brzustewicz",
      "dustin-wolf",
      "devin-cooley",
      "jacob-markstrom",
      "rasmus-andersson",
      "nazem-kadri",
      "daniil-miromanov",
      "parker-bell",
      "lucas-ciona",
      "andrew-basha",
      "carter-king",
      "aydar-suniev",
      "clark-bishop",
      "rory-kerins",
      "sam-morton",
      "william-stromgren",
      "dryden-hunt",
      "justin-kirkland",
      "tyson-gross",
      "brennan-othmann",
      "artem-grushnikov",
      "etienne-morin",
      "nick-cicek",
      "daniil-miromanov",
      "gavin-white",
      "arsenii-sergeev",
      "ivan-prosvetov",
      "owen-say",
      "daniil-chechelev",
      "trevor-hoskin",
      "axel-hurtig",
      "eric-jamieson",
      "pavel-karnaukhov",
      "demetrios-koumontzis",
      "hunter-laing",
      "cade-littler",
      "henry-mews",
      "luke-misa",
      "yegor-yegorov",
      "kirill-zarubin",
      "rushan-rafikov",
      "cole-reschny",
      "cullen-potter",
      "theo-stockselius",
      "maceo-phillips",
      "ethan-wyttenbach",
      "aidan-lane",
      "jakob-leander",
      "yan-matveiko",
      "abram-wiebe",
      "jonathan-castagna",
      "maxmilian-curran"
    ],
    "projections": null,
    "goals": [
      {
        "gameId": 2025020151,
        "goalIndex": 3,
        "date": "2025-10-28",
        "opponentTricode": "TOR",
        "shotType": "wrist",
        "goalClassification": "Rush"
      },
      {
        "gameId": 2025020183,
        "goalIndex": 5,
        "date": "2025-11-01",
        "opponentTricode": "NSH",
        "shotType": "wrist",
        "goalClassification": "Broken Coverage"
      },
      {
        "gameId": 2025020316,
        "goalIndex": 2,
        "date": "2025-11-19",
        "opponentTricode": "BUF",
        "shotType": "tip-in",
        "goalClassification": "Cycle"
      },
      {
        "gameId": 2025020316,
        "goalIndex": 7,
        "date": "2025-11-19",
        "opponentTricode": "BUF",
        "shotType": "wrist",
        "goalClassification": "Rush"
      },
      {
        "gameId": 2025020345,
        "goalIndex": 2,
        "date": "2025-11-22",
        "opponentTricode": "DAL",
        "shotType": "deflected",
        "goalClassification": "Net-front"
      },
      {
        "gameId": 2025020362,
        "goalIndex": 5,
        "date": "2025-11-26",
        "opponentTricode": "TBL",
        "shotType": "wrist",
        "goalClassification": "Broken Coverage"
      },
      {
        "gameId": 2025020380,
        "goalIndex": 8,
        "date": "2025-11-28",
        "opponentTricode": "FLA",
        "shotType": "snap",
        "goalClassification": "Empty Net"
      },
      {
        "gameId": 2025020477,
        "goalIndex": 5,
        "date": "2025-12-10",
        "opponentTricode": "DET",
        "shotType": "wrist",
        "goalClassification": "Seam"
      },
      {
        "gameId": 2025020559,
        "goalIndex": 6,
        "date": "2025-12-20",
        "opponentTricode": "VGK",
        "shotType": "wrist",
        "goalClassification": "Rebound/Scramble"
      },
      {
        "gameId": 2025020678,
        "goalIndex": 4,
        "date": "2026-01-07",
        "opponentTricode": "MTL",
        "shotType": "snap",
        "goalClassification": "Rush"
      },
      {
        "gameId": 2025020863,
        "goalIndex": 5,
        "date": "2026-01-31",
        "opponentTricode": "SJS",
        "shotType": "backhand",
        "goalClassification": "Rush"
      },
      {
        "gameId": 2025020885,
        "goalIndex": 5,
        "date": "2026-02-02",
        "opponentTricode": "TOR",
        "shotType": "tip-in",
        "goalClassification": "Cycle"
      },
      {
        "gameId": 2025020998,
        "goalIndex": 3,
        "date": "2026-03-07",
        "opponentTricode": "CAR",
        "shotType": "wrist",
        "goalClassification": "Cycle"
      },
      {
        "gameId": 2025020998,
        "goalIndex": 8,
        "date": "2026-03-07",
        "opponentTricode": "CAR",
        "shotType": "backhand",
        "goalClassification": "Rush"
      }
    ]
}
