/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlayersIndexRouteImport } from './routes/players/index'
import { Route as CbaIndexRouteImport } from './routes/cba/index'
import { Route as TeamsTeamSlugRouteImport } from './routes/teams/$teamSlug'
import { Route as StaffStaffSlugRouteImport } from './routes/staff/$staffSlug'
import { Route as PlayersPlayerSlugRouteImport } from './routes/players/$playerSlug'
import { Route as CbaPlayersRouteImport } from './routes/cba/players'
import { Route as CbaCbaRouteImport } from './routes/cba/cba'
import { Route as CalculatorsContractVariabilityRouteImport } from './routes/calculators/contract-variability'
import { Route as TeamsTeamSlugDepthChartRouteImport } from './routes/teams/$teamSlug.depth-chart'
import { Route as TeamsTeamSlugDailyCapRouteImport } from './routes/teams/$teamSlug.daily-cap'
import { Route as CalculatorsBuyoutCustomRouteImport } from './routes/calculators/buyout.custom'
import { Route as ApiV1SearchRouteImport } from './routes/api.v1/search'
import { Route as ApiV1StaffIndexRouteImport } from './routes/api.v1/staff/index'
import { Route as ApiV1TeamsTeamSlugRouteRouteImport } from './routes/api.v1/teams/$teamSlug/route'
import { Route as ApiV1PlayersPlayerSlugRouteRouteImport } from './routes/api/v1/players/$playerSlug/route'
import { Route as ApiV1DraftsDraftYearRouteRouteImport } from './routes/api/v1/drafts/$draftYear/route'

const AboutLazyRouteImport = createFileRoute('/about')()
const IndexLazyRouteImport = createFileRoute('/')()
const ToolsCustomDraftLotteryLazyRouteImport = createFileRoute(
  '/tools/custom-draft-lottery',
)()

const AboutLazyRoute = AboutLazyRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))
const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const PlayersIndexRoute = PlayersIndexRouteImport.update({
  id: '/players/',
  path: '/players/',
  getParentRoute: () => rootRouteImport,
} as any)
const CbaIndexRoute = CbaIndexRouteImport.update({
  id: '/cba/',
  path: '/cba/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsCustomDraftLotteryLazyRoute =
  ToolsCustomDraftLotteryLazyRouteImport.update({
    id: '/tools/custom-draft-lottery',
    path: '/tools/custom-draft-lottery',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/tools/custom-draft-lottery.lazy').then((d) => d.Route),
  )
const TeamsTeamSlugRoute = TeamsTeamSlugRouteImport.update({
  id: '/teams/$teamSlug',
  path: '/teams/$teamSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffStaffSlugRoute = StaffStaffSlugRouteImport.update({
  id: '/staff/$staffSlug',
  path: '/staff/$staffSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersPlayerSlugRoute = PlayersPlayerSlugRouteImport.update({
  id: '/players/$playerSlug',
  path: '/players/$playerSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const CbaPlayersRoute = CbaPlayersRouteImport.update({
  id: '/cba/players',
  path: '/cba/players',
  getParentRoute: () => rootRouteImport,
} as any)
const CbaCbaRoute = CbaCbaRouteImport.update({
  id: '/cba/cba',
  path: '/cba/cba',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorsContractVariabilityRoute =
  CalculatorsContractVariabilityRouteImport.update({
    id: '/calculators/contract-variability',
    path: '/calculators/contract-variability',
    getParentRoute: () => rootRouteImport,
  } as any)
const TeamsTeamSlugDepthChartRoute = TeamsTeamSlugDepthChartRouteImport.update({
  id: '/depth-chart',
  path: '/depth-chart',
  getParentRoute: () => TeamsTeamSlugRoute,
} as any)
const TeamsTeamSlugDailyCapRoute = TeamsTeamSlugDailyCapRouteImport.update({
  id: '/daily-cap',
  path: '/daily-cap',
  getParentRoute: () => TeamsTeamSlugRoute,
} as any)
const CalculatorsBuyoutCustomRoute = CalculatorsBuyoutCustomRouteImport.update({
  id: '/calculators/buyout/custom',
  path: '/calculators/buyout/custom',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1SearchRoute = ApiV1SearchRouteImport.update({
  id: '/api/v1/search',
  path: '/api/v1/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1StaffIndexRoute = ApiV1StaffIndexRouteImport.update({
  id: '/api/v1/staff/',
  path: '/api/v1/staff/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1TeamsTeamSlugRouteRoute = ApiV1TeamsTeamSlugRouteRouteImport.update({
  id: '/api/v1/teams/$teamSlug',
  path: '/api/v1/teams/$teamSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1PlayersPlayerSlugRouteRoute =
  ApiV1PlayersPlayerSlugRouteRouteImport.update({
    id: '/api/v1/players/$playerSlug',
    path: '/api/v1/players/$playerSlug',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1DraftsDraftYearRouteRoute =
  ApiV1DraftsDraftYearRouteRouteImport.update({
    id: '/api/v1/drafts/$draftYear',
    path: '/api/v1/drafts/$draftYear',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/about': typeof AboutLazyRoute
  '/calculators/contract-variability': typeof CalculatorsContractVariabilityRoute
  '/cba/cba': typeof CbaCbaRoute
  '/cba/players': typeof CbaPlayersRoute
  '/players/$playerSlug': typeof PlayersPlayerSlugRoute
  '/staff/$staffSlug': typeof StaffStaffSlugRoute
  '/teams/$teamSlug': typeof TeamsTeamSlugRouteWithChildren
  '/tools/custom-draft-lottery': typeof ToolsCustomDraftLotteryLazyRoute
  '/cba/': typeof CbaIndexRoute
  '/players/': typeof PlayersIndexRoute
  '/api/v1/search': typeof ApiV1SearchRoute
  '/calculators/buyout/custom': typeof CalculatorsBuyoutCustomRoute
  '/teams/$teamSlug/daily-cap': typeof TeamsTeamSlugDailyCapRoute
  '/teams/$teamSlug/depth-chart': typeof TeamsTeamSlugDepthChartRoute
  '/api/v1/drafts/$draftYear': typeof ApiV1DraftsDraftYearRouteRoute
  '/api/v1/players/$playerSlug': typeof ApiV1PlayersPlayerSlugRouteRoute
  '/api/v1/teams/$teamSlug': typeof ApiV1TeamsTeamSlugRouteRoute
  '/api/v1/staff/': typeof ApiV1StaffIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/about': typeof AboutLazyRoute
  '/calculators/contract-variability': typeof CalculatorsContractVariabilityRoute
  '/cba/cba': typeof CbaCbaRoute
  '/cba/players': typeof CbaPlayersRoute
  '/players/$playerSlug': typeof PlayersPlayerSlugRoute
  '/staff/$staffSlug': typeof StaffStaffSlugRoute
  '/teams/$teamSlug': typeof TeamsTeamSlugRouteWithChildren
  '/tools/custom-draft-lottery': typeof ToolsCustomDraftLotteryLazyRoute
  '/cba': typeof CbaIndexRoute
  '/players': typeof PlayersIndexRoute
  '/api/v1/search': typeof ApiV1SearchRoute
  '/calculators/buyout/custom': typeof CalculatorsBuyoutCustomRoute
  '/teams/$teamSlug/daily-cap': typeof TeamsTeamSlugDailyCapRoute
  '/teams/$teamSlug/depth-chart': typeof TeamsTeamSlugDepthChartRoute
  '/api/v1/drafts/$draftYear': typeof ApiV1DraftsDraftYearRouteRoute
  '/api/v1/players/$playerSlug': typeof ApiV1PlayersPlayerSlugRouteRoute
  '/api/v1/teams/$teamSlug': typeof ApiV1TeamsTeamSlugRouteRoute
  '/api/v1/staff': typeof ApiV1StaffIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/about': typeof AboutLazyRoute
  '/calculators/contract-variability': typeof CalculatorsContractVariabilityRoute
  '/cba/cba': typeof CbaCbaRoute
  '/cba/players': typeof CbaPlayersRoute
  '/players/$playerSlug': typeof PlayersPlayerSlugRoute
  '/staff/$staffSlug': typeof StaffStaffSlugRoute
  '/teams/$teamSlug': typeof TeamsTeamSlugRouteWithChildren
  '/tools/custom-draft-lottery': typeof ToolsCustomDraftLotteryLazyRoute
  '/cba/': typeof CbaIndexRoute
  '/players/': typeof PlayersIndexRoute
  '/api/v1/search': typeof ApiV1SearchRoute
  '/calculators/buyout/custom': typeof CalculatorsBuyoutCustomRoute
  '/teams/$teamSlug/daily-cap': typeof TeamsTeamSlugDailyCapRoute
  '/teams/$teamSlug/depth-chart': typeof TeamsTeamSlugDepthChartRoute
  '/api/v1/drafts/$draftYear': typeof ApiV1DraftsDraftYearRouteRoute
  '/api/v1/players/$playerSlug': typeof ApiV1PlayersPlayerSlugRouteRoute
  '/api/v1/teams/$teamSlug': typeof ApiV1TeamsTeamSlugRouteRoute
  '/api/v1/staff/': typeof ApiV1StaffIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/calculators/contract-variability'
    | '/cba/cba'
    | '/cba/players'
    | '/players/$playerSlug'
    | '/staff/$staffSlug'
    | '/teams/$teamSlug'
    | '/tools/custom-draft-lottery'
    | '/cba/'
    | '/players/'
    | '/api/v1/search'
    | '/calculators/buyout/custom'
    | '/teams/$teamSlug/daily-cap'
    | '/teams/$teamSlug/depth-chart'
    | '/api/v1/drafts/$draftYear'
    | '/api/v1/players/$playerSlug'
    | '/api/v1/teams/$teamSlug'
    | '/api/v1/staff/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/calculators/contract-variability'
    | '/cba/cba'
    | '/cba/players'
    | '/players/$playerSlug'
    | '/staff/$staffSlug'
    | '/teams/$teamSlug'
    | '/tools/custom-draft-lottery'
    | '/cba'
    | '/players'
    | '/api/v1/search'
    | '/calculators/buyout/custom'
    | '/teams/$teamSlug/daily-cap'
    | '/teams/$teamSlug/depth-chart'
    | '/api/v1/drafts/$draftYear'
    | '/api/v1/players/$playerSlug'
    | '/api/v1/teams/$teamSlug'
    | '/api/v1/staff'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/calculators/contract-variability'
    | '/cba/cba'
    | '/cba/players'
    | '/players/$playerSlug'
    | '/staff/$staffSlug'
    | '/teams/$teamSlug'
    | '/tools/custom-draft-lottery'
    | '/cba/'
    | '/players/'
    | '/api/v1/search'
    | '/calculators/buyout/custom'
    | '/teams/$teamSlug/daily-cap'
    | '/teams/$teamSlug/depth-chart'
    | '/api/v1/drafts/$draftYear'
    | '/api/v1/players/$playerSlug'
    | '/api/v1/teams/$teamSlug'
    | '/api/v1/staff/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AboutLazyRoute: typeof AboutLazyRoute
  CalculatorsContractVariabilityRoute: typeof CalculatorsContractVariabilityRoute
  CbaCbaRoute: typeof CbaCbaRoute
  CbaPlayersRoute: typeof CbaPlayersRoute
  PlayersPlayerSlugRoute: typeof PlayersPlayerSlugRoute
  StaffStaffSlugRoute: typeof StaffStaffSlugRoute
  TeamsTeamSlugRoute: typeof TeamsTeamSlugRouteWithChildren
  ToolsCustomDraftLotteryLazyRoute: typeof ToolsCustomDraftLotteryLazyRoute
  CbaIndexRoute: typeof CbaIndexRoute
  PlayersIndexRoute: typeof PlayersIndexRoute
  ApiV1SearchRoute: typeof ApiV1SearchRoute
  CalculatorsBuyoutCustomRoute: typeof CalculatorsBuyoutCustomRoute
  ApiV1DraftsDraftYearRouteRoute: typeof ApiV1DraftsDraftYearRouteRoute
  ApiV1PlayersPlayerSlugRouteRoute: typeof ApiV1PlayersPlayerSlugRouteRoute
  ApiV1TeamsTeamSlugRouteRoute: typeof ApiV1TeamsTeamSlugRouteRoute
  ApiV1StaffIndexRoute: typeof ApiV1StaffIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players/': {
      id: '/players/'
      path: '/players'
      fullPath: '/players/'
      preLoaderRoute: typeof PlayersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cba/': {
      id: '/cba/'
      path: '/cba'
      fullPath: '/cba/'
      preLoaderRoute: typeof CbaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/custom-draft-lottery': {
      id: '/tools/custom-draft-lottery'
      path: '/tools/custom-draft-lottery'
      fullPath: '/tools/custom-draft-lottery'
      preLoaderRoute: typeof ToolsCustomDraftLotteryLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/$teamSlug': {
      id: '/teams/$teamSlug'
      path: '/teams/$teamSlug'
      fullPath: '/teams/$teamSlug'
      preLoaderRoute: typeof TeamsTeamSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/$staffSlug': {
      id: '/staff/$staffSlug'
      path: '/staff/$staffSlug'
      fullPath: '/staff/$staffSlug'
      preLoaderRoute: typeof StaffStaffSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players/$playerSlug': {
      id: '/players/$playerSlug'
      path: '/players/$playerSlug'
      fullPath: '/players/$playerSlug'
      preLoaderRoute: typeof PlayersPlayerSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cba/players': {
      id: '/cba/players'
      path: '/cba/players'
      fullPath: '/cba/players'
      preLoaderRoute: typeof CbaPlayersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cba/cba': {
      id: '/cba/cba'
      path: '/cba/cba'
      fullPath: '/cba/cba'
      preLoaderRoute: typeof CbaCbaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculators/contract-variability': {
      id: '/calculators/contract-variability'
      path: '/calculators/contract-variability'
      fullPath: '/calculators/contract-variability'
      preLoaderRoute: typeof CalculatorsContractVariabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/$teamSlug/depth-chart': {
      id: '/teams/$teamSlug/depth-chart'
      path: '/depth-chart'
      fullPath: '/teams/$teamSlug/depth-chart'
      preLoaderRoute: typeof TeamsTeamSlugDepthChartRouteImport
      parentRoute: typeof TeamsTeamSlugRoute
    }
    '/teams/$teamSlug/daily-cap': {
      id: '/teams/$teamSlug/daily-cap'
      path: '/daily-cap'
      fullPath: '/teams/$teamSlug/daily-cap'
      preLoaderRoute: typeof TeamsTeamSlugDailyCapRouteImport
      parentRoute: typeof TeamsTeamSlugRoute
    }
    '/calculators/buyout/custom': {
      id: '/calculators/buyout/custom'
      path: '/calculators/buyout/custom'
      fullPath: '/calculators/buyout/custom'
      preLoaderRoute: typeof CalculatorsBuyoutCustomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/search': {
      id: '/api/v1/search'
      path: '/api/v1/search'
      fullPath: '/api/v1/search'
      preLoaderRoute: typeof ApiV1SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/staff/': {
      id: '/api/v1/staff/'
      path: '/api/v1/staff'
      fullPath: '/api/v1/staff/'
      preLoaderRoute: typeof ApiV1StaffIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/teams/$teamSlug': {
      id: '/api/v1/teams/$teamSlug'
      path: '/api/v1/teams/$teamSlug'
      fullPath: '/api/v1/teams/$teamSlug'
      preLoaderRoute: typeof ApiV1TeamsTeamSlugRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/players/$playerSlug': {
      id: '/api/v1/players/$playerSlug'
      path: '/api/v1/players/$playerSlug'
      fullPath: '/api/v1/players/$playerSlug'
      preLoaderRoute: typeof ApiV1PlayersPlayerSlugRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/drafts/$draftYear': {
      id: '/api/v1/drafts/$draftYear'
      path: '/api/v1/drafts/$draftYear'
      fullPath: '/api/v1/drafts/$draftYear'
      preLoaderRoute: typeof ApiV1DraftsDraftYearRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface TeamsTeamSlugRouteChildren {
  TeamsTeamSlugDailyCapRoute: typeof TeamsTeamSlugDailyCapRoute
  TeamsTeamSlugDepthChartRoute: typeof TeamsTeamSlugDepthChartRoute
}

const TeamsTeamSlugRouteChildren: TeamsTeamSlugRouteChildren = {
  TeamsTeamSlugDailyCapRoute: TeamsTeamSlugDailyCapRoute,
  TeamsTeamSlugDepthChartRoute: TeamsTeamSlugDepthChartRoute,
}

const TeamsTeamSlugRouteWithChildren = TeamsTeamSlugRoute._addFileChildren(
  TeamsTeamSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AboutLazyRoute: AboutLazyRoute,
  CalculatorsContractVariabilityRoute: CalculatorsContractVariabilityRoute,
  CbaCbaRoute: CbaCbaRoute,
  CbaPlayersRoute: CbaPlayersRoute,
  PlayersPlayerSlugRoute: PlayersPlayerSlugRoute,
  StaffStaffSlugRoute: StaffStaffSlugRoute,
  TeamsTeamSlugRoute: TeamsTeamSlugRouteWithChildren,
  ToolsCustomDraftLotteryLazyRoute: ToolsCustomDraftLotteryLazyRoute,
  CbaIndexRoute: CbaIndexRoute,
  PlayersIndexRoute: PlayersIndexRoute,
  ApiV1SearchRoute: ApiV1SearchRoute,
  CalculatorsBuyoutCustomRoute: CalculatorsBuyoutCustomRoute,
  ApiV1DraftsDraftYearRouteRoute: ApiV1DraftsDraftYearRouteRoute,
  ApiV1PlayersPlayerSlugRouteRoute: ApiV1PlayersPlayerSlugRouteRoute,
  ApiV1TeamsTeamSlugRouteRoute: ApiV1TeamsTeamSlugRouteRoute,
  ApiV1StaffIndexRoute: ApiV1StaffIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
