/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeamsTeamSlugRouteImport } from './routes/teams/$teamSlug'
import { Route as StaffStaffSlugRouteImport } from './routes/staff/$staffSlug'
import { Route as PlayersPlayerSlugRouteImport } from './routes/players/$playerSlug'
import { Route as CalculatorsContractVariabilityRouteImport } from './routes/calculators/contract-variability'
import { Route as TeamsTeamSlugDepthChartRouteImport } from './routes/teams/$teamSlug.depth-chart'
import { Route as TeamsTeamSlugDailyCapRouteImport } from './routes/teams/$teamSlug.daily-cap'
import { Route as CalculatorsBuyoutCustomRouteImport } from './routes/calculators/buyout.custom'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsTeamSlugRoute = TeamsTeamSlugRouteImport.update({
  id: '/teams/$teamSlug',
  path: '/teams/$teamSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffStaffSlugRoute = StaffStaffSlugRouteImport.update({
  id: '/staff/$staffSlug',
  path: '/staff/$staffSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersPlayerSlugRoute = PlayersPlayerSlugRouteImport.update({
  id: '/players/$playerSlug',
  path: '/players/$playerSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorsContractVariabilityRoute =
  CalculatorsContractVariabilityRouteImport.update({
    id: '/calculators/contract-variability',
    path: '/calculators/contract-variability',
    getParentRoute: () => rootRouteImport,
  } as any)
const TeamsTeamSlugDepthChartRoute = TeamsTeamSlugDepthChartRouteImport.update({
  id: '/depth-chart',
  path: '/depth-chart',
  getParentRoute: () => TeamsTeamSlugRoute,
} as any)
const TeamsTeamSlugDailyCapRoute = TeamsTeamSlugDailyCapRouteImport.update({
  id: '/daily-cap',
  path: '/daily-cap',
  getParentRoute: () => TeamsTeamSlugRoute,
} as any)
const CalculatorsBuyoutCustomRoute = CalculatorsBuyoutCustomRouteImport.update({
  id: '/calculators/buyout/custom',
  path: '/calculators/buyout/custom',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/calculators/contract-variability': typeof CalculatorsContractVariabilityRoute
  '/players/$playerSlug': typeof PlayersPlayerSlugRoute
  '/staff/$staffSlug': typeof StaffStaffSlugRoute
  '/teams/$teamSlug': typeof TeamsTeamSlugRouteWithChildren
  '/calculators/buyout/custom': typeof CalculatorsBuyoutCustomRoute
  '/teams/$teamSlug/daily-cap': typeof TeamsTeamSlugDailyCapRoute
  '/teams/$teamSlug/depth-chart': typeof TeamsTeamSlugDepthChartRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/calculators/contract-variability': typeof CalculatorsContractVariabilityRoute
  '/players/$playerSlug': typeof PlayersPlayerSlugRoute
  '/staff/$staffSlug': typeof StaffStaffSlugRoute
  '/teams/$teamSlug': typeof TeamsTeamSlugRouteWithChildren
  '/calculators/buyout/custom': typeof CalculatorsBuyoutCustomRoute
  '/teams/$teamSlug/daily-cap': typeof TeamsTeamSlugDailyCapRoute
  '/teams/$teamSlug/depth-chart': typeof TeamsTeamSlugDepthChartRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/calculators/contract-variability': typeof CalculatorsContractVariabilityRoute
  '/players/$playerSlug': typeof PlayersPlayerSlugRoute
  '/staff/$staffSlug': typeof StaffStaffSlugRoute
  '/teams/$teamSlug': typeof TeamsTeamSlugRouteWithChildren
  '/calculators/buyout/custom': typeof CalculatorsBuyoutCustomRoute
  '/teams/$teamSlug/daily-cap': typeof TeamsTeamSlugDailyCapRoute
  '/teams/$teamSlug/depth-chart': typeof TeamsTeamSlugDepthChartRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/calculators/contract-variability'
    | '/players/$playerSlug'
    | '/staff/$staffSlug'
    | '/teams/$teamSlug'
    | '/calculators/buyout/custom'
    | '/teams/$teamSlug/daily-cap'
    | '/teams/$teamSlug/depth-chart'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/calculators/contract-variability'
    | '/players/$playerSlug'
    | '/staff/$staffSlug'
    | '/teams/$teamSlug'
    | '/calculators/buyout/custom'
    | '/teams/$teamSlug/daily-cap'
    | '/teams/$teamSlug/depth-chart'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/calculators/contract-variability'
    | '/players/$playerSlug'
    | '/staff/$staffSlug'
    | '/teams/$teamSlug'
    | '/calculators/buyout/custom'
    | '/teams/$teamSlug/daily-cap'
    | '/teams/$teamSlug/depth-chart'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CalculatorsContractVariabilityRoute: typeof CalculatorsContractVariabilityRoute
  PlayersPlayerSlugRoute: typeof PlayersPlayerSlugRoute
  StaffStaffSlugRoute: typeof StaffStaffSlugRoute
  TeamsTeamSlugRoute: typeof TeamsTeamSlugRouteWithChildren
  CalculatorsBuyoutCustomRoute: typeof CalculatorsBuyoutCustomRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/$teamSlug': {
      id: '/teams/$teamSlug'
      path: '/teams/$teamSlug'
      fullPath: '/teams/$teamSlug'
      preLoaderRoute: typeof TeamsTeamSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/$staffSlug': {
      id: '/staff/$staffSlug'
      path: '/staff/$staffSlug'
      fullPath: '/staff/$staffSlug'
      preLoaderRoute: typeof StaffStaffSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players/$playerSlug': {
      id: '/players/$playerSlug'
      path: '/players/$playerSlug'
      fullPath: '/players/$playerSlug'
      preLoaderRoute: typeof PlayersPlayerSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculators/contract-variability': {
      id: '/calculators/contract-variability'
      path: '/calculators/contract-variability'
      fullPath: '/calculators/contract-variability'
      preLoaderRoute: typeof CalculatorsContractVariabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/$teamSlug/depth-chart': {
      id: '/teams/$teamSlug/depth-chart'
      path: '/depth-chart'
      fullPath: '/teams/$teamSlug/depth-chart'
      preLoaderRoute: typeof TeamsTeamSlugDepthChartRouteImport
      parentRoute: typeof TeamsTeamSlugRoute
    }
    '/teams/$teamSlug/daily-cap': {
      id: '/teams/$teamSlug/daily-cap'
      path: '/daily-cap'
      fullPath: '/teams/$teamSlug/daily-cap'
      preLoaderRoute: typeof TeamsTeamSlugDailyCapRouteImport
      parentRoute: typeof TeamsTeamSlugRoute
    }
    '/calculators/buyout/custom': {
      id: '/calculators/buyout/custom'
      path: '/calculators/buyout/custom'
      fullPath: '/calculators/buyout/custom'
      preLoaderRoute: typeof CalculatorsBuyoutCustomRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface TeamsTeamSlugRouteChildren {
  TeamsTeamSlugDailyCapRoute: typeof TeamsTeamSlugDailyCapRoute
  TeamsTeamSlugDepthChartRoute: typeof TeamsTeamSlugDepthChartRoute
}

const TeamsTeamSlugRouteChildren: TeamsTeamSlugRouteChildren = {
  TeamsTeamSlugDailyCapRoute: TeamsTeamSlugDailyCapRoute,
  TeamsTeamSlugDepthChartRoute: TeamsTeamSlugDepthChartRoute,
}

const TeamsTeamSlugRouteWithChildren = TeamsTeamSlugRoute._addFileChildren(
  TeamsTeamSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CalculatorsContractVariabilityRoute: CalculatorsContractVariabilityRoute,
  PlayersPlayerSlugRoute: PlayersPlayerSlugRoute,
  StaffStaffSlugRoute: StaffStaffSlugRoute,
  TeamsTeamSlugRoute: TeamsTeamSlugRouteWithChildren,
  CalculatorsBuyoutCustomRoute: CalculatorsBuyoutCustomRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
